In [4]:

import numpy 
#Original Matrix
matrix = [[1,2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13,14, 15, 16]]
# Transpose of the given 4*4 matrix
print(numpy.transpose(matrix))
mat=np.transpose(matrix)
print(mat.reshape((2,8)))


[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
[[ 1  5  9 13  2  6 10 14]
 [ 3  7 11 15  4  8 12 16]]


In [ ]:
#plotting graph between two points
import matplotlib.pyplot as plt
import numpy as np

xpts = np.array([1,5])
ypts = np.array([6,8])

plt.plot(xpts, ypts)
plt.xlabel('x - axis')
plt.ylabel('y - axis')
plt.title('Graph between two points')  
plt.show()

In [ ]:
# PLotting multiple points
import matplotlib.pyplot as plt
import numpy as np
xpts = np.array([8, 4, 2, 1])
ypts = np.array([5, 6, 7, 8])
plt.plot(xpts, ypts)
plt.xlabel('x - axis')
plt.ylabel('y - axis')
plt.title('Plotting multiple points')
plt.show()

In [ ]:
#Plotting two graphs together
import matplotlib.pyplot as plt
x1 = [3,2,7]
y1 = [1,5,3] 
plt.plot(x1, y1, label = "graph 1")
x2 = [1,1,3]
y2 = [4,1,3] 
plt.plot(x2, y2, label = "graph 2")
plt.xlabel('x - axis')
plt.ylabel('y - axis')
plt.title('')
plt.legend()
plt.show()